/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace Customer {
    export interface CustomerService {
        login(
            data: LoginT1Req,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<LoginT1Res>;
        signUp(
            data: SignUpT1Req,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<SignUpT1Res>;
    }
    export interface ById {
        id?: number;
    }
    export interface LoginT1Req {
        usr?: string;
        password?: string;
    }
    export interface LoginT1Res {
        status?: number;
        uid?: number;
        type?: string;
        role?: string;
        fcmToken?: string;
    }
    export interface SignUpT1Req {
        usr?: string;
        password?: string;
        inviteCode?: string;
    }
    export interface SignUpT1Res {
        status?: number;
        uid?: number;
    }
}

